### PR TITLE
Have latest telemetry always be delivered to consumers

### LINKED ISSUE #271: Potential for telemetry to be "missed" by subscribers
#### Summary
[An optimization in the openmct-yamcs plugin](https://github.com/akhenry/openmct-yamcs/blob/80b9d96979a27fec4f60e1cc3f1c84b4162eab65/src/providers/historical-telemetry-provider.js#L59) short-circuits requests for latest data in real-time mode with the assumption that [a subsequent subscription callback will provide the requested data](https://github.com/akhenry/openmct-yamcs/blob/80b9d96979a27fec4f60e1cc3f1c84b4162eab65/src/providers/messages.js#L62).

This creates an edge-case that we should address, ~~and some investigation to see whether it's actually replicable in our current codebase~~. It is.

The Telemetry API [multiplexes multiple subscriptions down to just a single provider subscription](https://github.com/nasa/openmct/blob/87901834bb8dc78b0a800b47cb1d9b484936d062/src/api/telemetry/TelemetryAPI.js#L409). The working assumption in our latest data optimization is that Yamcs will provide us with the latest telemetry value immediately upon subscription. However this assumption fails in some cases due to the previously mentioned multiplexing.

If client code subscribes to a parameter that does not update very often, and for whatever reason misses the initial subscription callback that includes the latest value, it will have no data until the telemetry point next updates. There are many, many reasons why client code might miss the initial subscription callback because of the asynchronous nature of how Open MCT operates.

#### Expected vs Current Behavior
Calling code should always receive the latest data when requested.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
~~Unknown, investigation required.~~ I believe that this issue has been recreated in https://github.com/nasa/openmct/pull/6108#issuecomment-1399041117

### PR DESCRIPTION
**Pull request by scottbell**
Closes #271 

### Describe your changes:
If asking for latest in historical telemetry provider, defer to the latest telemetry provider for batched retrieval.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/providers/latest-telemetry-provider.js [hunk 1]
```diff
@@ -119,9 +121,14 @@ export default class LatestTelemetryProvider {
         this.#bulkPromise = undefined;
     }
 
-    #waitOneEventCycle() {
+    #waitForDebounce() {
```
Comment (akhenry) [inline src/providers/latest-telemetry-provider.js:124]: I had completely forgotten that batching was already implemented! The previous method did not use true debouncing, consequently the way that this function is called will never truly debounce the call either. I think it will _always_ wait 100ms no matter what, right? Because we are basically using the presence of `this.#bulkPromise` as a semaphore.

It's fine how it is for now. We _might_ be able to improve this in future by removing the semaphore and having it always call the debounce function each time, which will keep clearing the timeout until it's settled down. We could then probably reduce or even remove the 100ms wait.

**Review by akhenry — APPROVED** [review]
Looks good to me. Will file a followup to tweak the debounce.

File: src/providers/latest-telemetry-provider.js (hunk 1 above)
Comment (scottbell) [reply src/providers/latest-telemetry-provider.js:124]: Sounds good!
